### ISSUE TITLE
script/server fails

### ISSUE THREAD

**Issue by Kadaaran** [education/classroom#1301]
All good when running `script/setup` but when I run `script/server` it yells at me this:

```
Users/kassandre/GitHub/classroom/lib/docker_compose/parser.rb:51:in `service_attributes': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/kassandre/GitHub/classroom/lib/docker_compose/parser.rb:38:in `block in parse'
	from /Users/kassandre/GitHub/classroom/lib/docker_compose/parser.rb:37:in `map'
	from /Users/kassandre/GitHub/classroom/lib/docker_compose/parser.rb:37:in `parse'
	from /Users/kassandre/GitHub/classroom/lib/docker_compose.rb:21:in `services_up?'
	from /Users/kassandre/GitHub/classroom/lib/docker_compose.rb:39:in `all_services_up?'
	from ./script/docker-services:16:in `block in <main>'
	from /Users/kassandre/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:120:in `chdir'
	from /Users/kassandre/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:120:in `cd'
	from ./script/docker-services:15:in `<main>'
```

I've been adding debug messages and it fails eventually on `lib/docker_compose/parser.rb:55` , I think we try to pop an array which was already under `.pop` earlier or something like that ?

**Comment by talsafran** [comment]
+1, I get this when I run `script/test`:

```
14:49 $ script/test
==> Ensuring Homebrew macOS dependencies...
Already up-to-date.
The Gemfile's dependencies are satisfied
yarn check v1.5.1
success Folder in sync.
✨  Done in 0.41s.
/Users/talsafran/github/classroom/lib/docker_compose/parser.rb:50:in `service_attributes': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/talsafran/github/classroom/lib/docker_compose/parser.rb:38:in `block in parse'
	from /Users/talsafran/github/classroom/lib/docker_compose/parser.rb:37:in `map'
	from /Users/talsafran/github/classroom/lib/docker_compose/parser.rb:37:in `parse'
	from /Users/talsafran/github/classroom/lib/docker_compose.rb:21:in `services_up?'
	from /Users/talsafran/github/classroom/lib/docker_compose.rb:39:in `all_services_up?'
	from ./script/docker-services:16:in `block in <main>'
	from /Users/talsafran/.rbenv/versions/2.4.2/lib/ruby/2.4.0/fileutils.rb:120:in `chdir'
	from /Users/talsafran/.rbenv/versions/2.4.2/lib/ruby/2.4.0/fileutils.rb:120:in `cd'
	from ./script/docker-services:15:in `<main>'
```

**Comment by Kadaaran** [comment]
All good now 👍

**Comment by Kadaaran** [comment]
Not fixed, it still happens randomly.

**Comment by Kadaaran** [comment]
I found out that I have to run `docker-compose stop` before `script/server` so it can relaunch the containers without any bugs.

I added a `sleep 5` just before the database setup, otherwise  PG tries to connect when the database is not all set yet.

https://github.com/education/classroom/blob/db93001fa86d84efa65a6ccca59645eceef4af46/script/setup#L17
