### ISSUE TITLE
running script/bootstrap script results in error

### ISSUE THREAD

**Issue by quiltykim** [education/classroom#1347]
Please choose either _issue_ or _feature request_

##
#### What you were trying to do ?
_I tried to run script/bootstrap ..._

#### What happened (include screenshot if you can) ?
_I got the following error: ..._

~/classroom/lib/docker_compose/parser.rb:50:in `service_attributes': undefined method `[]' for nil:NilClass (NoMethodError)
	from ~/classroom/lib/docker_compose/parser.rb:38:in `block in parse'
	from ~/classroom/lib/docker_compose/parser.rb:37:in `map'
	from ~/classroom/lib/docker_compose/parser.rb:37:in `parse'
	from ~/classroom/lib/docker_compose.rb:21:in `services_up?'
	from ~/classroom/lib/docker_compose.rb:39:in `all_services_up?'
	from ./script/docker-services:16:in `block in <main>'
	from ~/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:120:in `chdir'
	from ~/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:120:in `cd'
	from ./script/docker-services:15:in `<main>'

#### Step-by-step reproduction instructions
See above

**Comment by Kadaaran** [comment]
Hi @quiltykim do you still have this issue ? Can I help ?
