### ISSUE TITLE
SignalException raised on deployment

### ISSUE THREAD

**Issue by shaunakpp** [education/classroom#2185]
Whenever we deploy, our exception tracker gets noisy with the `SignalExcpetion` due to `Puma` receiving a SIGTERM. This is an expected behavior and should not be raised. It can be fixed adding `raise_exception_on_sigterm(false)` to our Puma config.

More information here:

https://github.com/puma/puma/pull/1690

**Needle**: https://haystack.githubapp.com/classroom/needles/zMtX4AGAjJVlre9rBQyzOA
**Rollup**: https://haystack.githubapp.com/classroom/rollups/194428943c1becce2f5745f9bb3a5ed8

```
SignalException
SIGTERM
```

<table>
  <thead>
    <tr>
      <th>attribute</th>
      <th>value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>argv</td>
      <td>./bin/puma -C config/puma.rb</td>
    </tr>
    <tr>
      <td>class_name</td>
      <td>SignalException</td>
    </tr>
    <tr>
      <td>halting</td>
      <td>true</td>
    </tr>
    <tr>
      <td>ruby</td>
      <td>ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]</td>
    </tr>

  </tbody>
</table>

<details>
<summary>Backtrace</summary>
<pre>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/puma-4.0.1/lib/puma/cluster.rb:419:in `block in setup_signals&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/puma-4.0.1/lib/puma/cluster.rb:514:in `select&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/puma-4.0.1/lib/puma/cluster.rb:514:in `run&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/puma-4.0.1/lib/puma/launcher.rb:186:in `run&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/puma-4.0.1/lib/puma/cli.rb:80:in `run&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/puma-4.0.1/bin/puma:10:in `&lt;top (required)&gt;&#39;</span>
<span class="l">./bin/puma:17:in `load&#39;</span>
<span class="l">./bin/puma:17:in `&lt;main&gt;&#39;</span>
</pre>
</details>

*Brought to you by Haystack's `!` hotkey.  Try it on a needle or rollup today!*

**Comment by shaunakpp** [comment]
solved by #2186
