### ISSUE TITLE
Gives error "You are forbidden from performing this action on github.com" if user does not approves his/her email

### ISSUE THREAD

**Issue by xaph** [education/classroom#364]
Hi,

If we invite an user who does not approve email on github.com, classroom gives an error like "You are forbidden from performing this action on github.com". User does not know anything about email approval and I think error message should be more clear.

**Comment by tarebyte** [comment]
@xaph I agree this error should be more descriptive, just to make sure I have this correct for testing, this is a new user who hasn't verified their email address on github.com correct?

**Comment by tarebyte** [comment]
@xaph I created a new user on GitHub without an email address and cannot reproduce the error.

Can you give me a step by step way or reproducing this?

**Comment by tarebyte** [comment]
:pager: @xaph

**Comment by xaph** [comment]
@tarebyte We got this error with 3 different users without email confirmation but we can't reproduce it now.

The steps we did:
- An admin creates a new assignment.
- Admin shares this assignment to a new user who didn't approve his/her email
- User clicks the assignment link and gets error.(I'm attaching the picture)
![screenshot_2015-11-18-22-16-07_1](https://cloud.githubusercontent.com/assets/124090/11339797/db80438e-9203-11e5-904b-55bbcb60e8b3.jpg)

I tried these steps several times after your response but didn't get the same error. Still, I'm writing these steps to give you some information about error.

**Comment by beydogan** [comment]
I was able to reproduce this error when I was testing on my local environment by;

- I signed in as User A
- I created a classroom
- I created an assignment 
- Opened new browser session and I go to invitation url and logged in as User A again.
- While logging in it removed some GitHub permissions like read/write permissions for repositories (that's the reason I believe)
- I click 'Accept this assignment'

Some part of backtrace of the exception;
```
/home/mehmet/RubymineProjects/classroom/app/models/concerns/git_hub.rb:37:in `raise_github_forbidden_error'
/home/mehmet/RubymineProjects/classroom/app/models/concerns/git_hub.rb:13:in `rescue in with_error_handling'
/home/mehmet/RubymineProjects/classroom/app/models/concerns/git_hub.rb:10:in `with_error_handling'
/home/mehmet/RubymineProjects/classroom/app/models/git_hub_organization.rb:41:in `create_repository'
/home/mehmet/RubymineProjects/classroom/app/models/concerns/git_hub_repoable.rb:24:in `create_github_repository'
/home/mehmet/RubymineProjects/classroom/app/models/group_assignment_repo.rb:22:in `block in <class:GroupAssignmentRepo>'
```

**Comment by bomeara** [comment]
About a quarter of my students are having this issue. Our assignment is at https://classroom.github.com/assignment-invitations/c28cc1d5a6c9e8151508df973ab23e70 .

**Comment by ajbraus** [comment]
+1

**Comment by johndbritton** [comment]
@tarebyte Can you look into this issue as well?

**Comment by nwoodthorpe** [comment]
I think this was somehow resolved. No activity in 15 months, closed!

**Comment by mstroutStudent** [comment]
I am now having this issue with a large class.  Even when the email addresses have been verified it is happening.  Could we reopen this issue?

**Comment by mstroutStudent** [comment]
It *might* be that github classroom just recently started checking that the email associated with the github account trying to accept the assignment has a .edu extension.  I am guessing this because when I changed my github "student" account to a .edu address, it started working.  Does anyone know if this is the case?

**Comment by greg2paris** [comment]
hi

**Comment by d12** [comment]
cc @education/classroom-reviewers

**Comment by d12** [comment]
Closing for inactivity, please re-open if this happens again.
