### ISSUE TITLE
Search index incomplete

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#440]
When using stafftools to find certain organizations and users, they don't appear as search results. This seems to be a problem with an incomplete search index.

@tarebyte can you take a look and perhaps rebuild the search index?

**Comment by johndbritton** [comment]
Running `rake chewy:reset` results in the following error:

```ruby
rake aborted!
NoMethodError: undefined method `title' for nil:NilClass
/app/app/chewy/stafftools_index.rb:31:in `block (2 levels) in <class:StafftoolsIndex>'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/fields/base.rb:39:in `compose'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/fields/base.rb:59:in `block in compose_children'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/fields/base.rb:59:in `map'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/fields/base.rb:59:in `compose_children'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/fields/base.rb:50:in `compose'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/type/import.rb:153:in `object_data'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/type/import.rb:123:in `index_bulk_entry'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/type/import.rb:82:in `block (2 levels) in bulk_body'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/type/import.rb:82:in `map'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/type/import.rb:82:in `block in bulk_body'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/type/import.rb:79:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/type/import.rb:79:in `inject'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/type/import.rb:79:in `bulk_body'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/type/import.rb:30:in `block (2 levels) in import'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/type/adapter/active_record.rb:32:in `import_scope'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/type/adapter/orm.rb:84:in `import'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/type/import.rb:28:in `block in import'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/type/import.rb:27:in `import'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/index/actions.rb:146:in `block in import'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/index/actions.rb:144:in `map'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/index/actions.rb:144:in `import'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/rake_helper.rb:50:in `update_index'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/rake_helper.rb:58:in `block in update_all'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/rake_helper.rb:58:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/chewy/rake_helper.rb:58:in `update_all'
/app/vendor/bundle/ruby/2.3.0/gems/chewy-0.8.2/lib/tasks/chewy.rake:30:in `block (2 levels) in <top (required)>'
```

**Comment by johndbritton** [comment]
Resolved in https://github.com/education/classroom/pull/492
