### ISSUE TITLE
Error running script/setup (Bundler::GemRequireError)

### ISSUE THREAD

**Issue by Nodraak** [education/classroom#467]
Hi !

I'm trying to setup Classroom inside a Docker container but I got an error when I run `script/setup`: ruby can't load the gem `autoprefixer-rails` although it seems to be installed as it should be (I have followed the README.md).

Here is the output of script/setup:

```bash
root@97bb49d8eb1d:~/classroom# script/setup 
==> Installing gem dependencies…
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Using rake 10.5.0
Using i18n 0.7.0

[...]

Using parser 2.2.2.6
Using autoprefixer-rails 6.0.3
Using uglifier 2.7.2

[...]

Using peek-sidekiq 1.0.0 from git://github.com/Soliah/peek-sidekiq.git (at 261c857@261c857)
Using jquery-turbolinks 2.1.0
Bundle complete! 56 Gemfile dependencies, 134 gems now installed.
Gems in the group production were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
===> Setting up DB...
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'autoprefixer-rails'. (Bundler::GemRequireError)
	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /root/classroom/config/application.rb:7:in `<top (required)>'
	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.4.0/lib/spring/application.rb:82:in `require'
	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.4.0/lib/spring/application.rb:82:in `preload'
	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.4.0/lib/spring/application.rb:143:in `serve'
	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.4.0/lib/spring/application.rb:131:in `block in run'
	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.4.0/lib/spring/application.rb:125:in `loop'
	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.4.0/lib/spring/application.rb:125:in `run'
	from /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.4.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /root/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /root/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

My Dockerfile:

```Dockerfile
FROM phusion/baseimage:0.9.18

WORKDIR /root

# install basic dep
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git wget

# es and heavy stuff
RUN wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
RUN echo "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-2.x.list
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql redis-server memcached openjdk-7-jre elasticsearch
RUN service postgresql start && service redis-server start && service memcached start && service elasticsearch start

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libssl-dev libreadline-dev zlib1g-dev libpq-dev

# rbenv
RUN git clone https://github.com/rbenv/rbenv.git ~/.rbenv
RUN cd ~/.rbenv && src/configure && make -C src

#RUN echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
ENV PATH="/root/.rbenv/bin:$PATH"

#RUN echo 'eval "$(rbenv init -)"' >> ~/.bashrc
ENV PATH="/root/.rbenv/shims:${PATH}"
ENV RBENV_SHELL=sh
RUN command rbenv rehash 2>/dev/null
RUN rbenv() { local command; command="$1"; if [ "$#" -gt 0 ]; then shift; fi; case "$command" in rehash|shell) eval "$(rbenv "sh-$command" "$@")";; *) command rbenv "$command" "$@";; esac ;}

# ruby-build
RUN git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

# ruby
RUN rbenv install 2.3.0
RUN rbenv global 2.3.0

# Classroom
RUN git clone https://github.com/education/classroom
WORKDIR /root/classroom

RUN gem install bundler && rbenv rehash

# workaround (git://url does not work)
RUN git clone 'http://github.com/Soliah/peek-sidekiq.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/peek-sidekiq-018f734a47db553ec3325306389f49eedf6d1348" --bare --no-hardlinks --quiet

RUN script/setup
```

Some more info, not sur if it will help:

```bash
root@97bb49d8eb1d:~/classroom# gem list | grep autoprefixer-rails
autoprefixer-rails (6.0.3)
root@97bb49d8eb1d:~/classroom# bundle show autoprefixer-rails
/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/autoprefixer-rails-6.0.3
root@97bb49d8eb1d:~/classroom# echo $PATH
/root/.rbenv/shims:/root/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@97bb49d8eb1d:~/classroom# which ruby
/root/.rbenv/shims/ruby
root@97bb49d8eb1d:~/classroom# ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
root@97bb49d8eb1d:~/classroom# which rbenv
/root/.rbenv/bin/rbenv
root@97bb49d8eb1d:~/classroom# rbenv --version
rbenv 1.0.0-19-g29b4da7
root@97bb49d8eb1d:~/classroom# which gem  
/root/.rbenv/shims/gem
root@97bb49d8eb1d:~/classroom# gem --version
2.5.1
```

Thanks for your help !

**Comment by tarebyte** [comment]
I have about 0 experience with docker so bare with me, doing a little bit of googling I think it because you don't have a javascript runtime dependency.

This might fix your problem

```diff
- RUN DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql redis-server memcached openjdk-7-jre elasticsearch
+ RUN DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql redis-server memcached openjdk-7-jre elasticsearch nodejs
```

**Comment by Nodraak** [comment]
Thank you very much, `nodejs` was indeed missing !
I read it nowhere in any documentation ... I will submit a PR to fix that, so no other noob get lost !
