### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by Aakash1312** [education/classroom#500]
I could successfully run the command `script/setup`
After changing .env file, I ran the command `script/server` and got the following error.

```
==> Updating db...
Warning: Running `gem pristine --all` to regenerate your installed gemspecs (and deleting then reinstalling your bundle if you use bundle --path) will improve the startup performance of Spring.
classroom_development already exists
01:57:08 web.1           | started with pid 10369
01:57:08 rails.1         | started with pid 10370
01:57:08 redis.1         | 10372:C 17 Mar 01:57:07.989 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
01:57:08 memcached.1     | started with pid 10373
01:57:08 worker.1        | started with pid 10379
01:57:08 elasticsearch.1 | unknown command: elasticsearch
01:57:08 rails.1         | JOIN pg_class t1 ON c.conrelid = t1.oid
01:57:08 redis.1         | 10372:M 17 Mar 01:57:07.990 * Increased maximum number of open files to 10032 (it was originally set to 1024).
01:57:08 rails.1         | JOIN pg_class t2 ON c.confrelid = t2.oid
01:57:08 redis.1         | 10372:M 17 Mar 01:57:07.991 # Creating Server TCP listening socket *:6379: bind: Address already in use
01:57:08 rails.1         | JOIN pg_attribute a1 ON a1.attnum = c.conkey[1] AND a1.attrelid = t1.oid
01:57:08 redis.1         | started with pid 10372
01:57:08 rails.1         | JOIN pg_attribute a2 ON a2.attnum = c.confkey[1] AND a2.attrelid = t2.oid
01:57:08 rails.1         | JOIN pg_namespace t3 ON c.connamespace = t3.oid
01:57:08 rails.1         | WHERE c.contype = 'f'
01:57:08 rails.1         |   AND t1.relname = 'users'
01:57:08 rails.1         |   AND t3.nspname = ANY (current_schemas(false))
01:57:08 rails.1         | ORDER BY c.conname
01:57:08 rails.1         | 
01:57:08 redis.1         | exited with code 1
01:57:08 system          | sending SIGTERM to all processes


/var/lib/gems/2.1.0/gems/foreman-0.78.0/lib/foreman/engine.rb:192:in **kill': no implicit conversion from nil to integer (TypeError)**
	from /var/lib/gems/2.1.0/gems/foreman-0.78.0/lib/foreman/engine.rb:192:in `kill_children'
	from /var/lib/gems/2.1.0/gems/foreman-0.78.0/lib/foreman/engine.rb:431:in `terminate_gracefully'
	from /var/lib/gems/2.1.0/gems/foreman-0.78.0/lib/foreman/engine.rb:60:in `block in start'
	from /var/lib/gems/2.1.0/gems/foreman-0.78.0/lib/foreman/engine.rb:417:in `watch_for_termination'
	from /var/lib/gems/2.1.0/gems/foreman-0.78.0/lib/foreman/engine.rb:60:in `start'
	from /var/lib/gems/2.1.0/gems/foreman-0.78.0/lib/foreman/cli.rb:41:in `start'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/2.1.0/gems/foreman-0.78.0/bin/foreman:7:in `<top (required)>'
	from /usr/local/bin/foreman:23:in `load'
	from /usr/local/bin/foreman:23:in `<main>'`
```

**Comment by tarebyte** [comment]
Hi @Aakash1312 it looks like you don't have redis or elasticsearch configured on your machine.

**Comment by johndbritton** [comment]
make sure you follow all the instructions here: https://github.com/education/classroom#installing-a-local-server

**Comment by Aakash1312** [comment]
Yes, I was able to do it. I killed all the redis-server background processes, then after running command again, I got it.

**Comment by sahilshekhawat** [comment]
Faced the same issue, should we add a note to the Readme?
